version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
    depends_on:
      - mongo
    environment:
      FLASK_APP: app.py 
      FLASK_ENV: development
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo_crud:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  mongo_crud:
    external: true
